<?php
$actfield = array(
	'realname' => array(
		'fieldid' => 'realname',
		'title' => '__DONT_DICONV_TO_UTF8___真实姓名',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'gender' => array(
		'fieldid' => 'gender',
		'title' => '__DONT_DICONV_TO_UTF8___性别',
		'formtype' => 'select',
		'default' => '__DONT_DICONV_TO_UTF8___保密',
		'size' => 0,
		'choices' => array('__DONT_DICONV_TO_UTF8___保密', '__DONT_DICONV_TO_UTF8___男', '__DONT_DICONV_TO_UTF8___女'),
		'validate' => '',
	),
	'birthday' => array(
		'fieldid' => 'birthday',
		'title' => '__DONT_DICONV_TO_UTF8___生日',
		'formtype' => 'datepicker',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'telephone' => array(
		'fieldid' => 'telephone',
		'title' => '__DONT_DICONV_TO_UTF8___固定电话',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'mobile' => array(
		'fieldid' => 'mobile',
		'title' => '__DONT_DICONV_TO_UTF8___手机',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'idcardtype' => array(
		'fieldid' => 'idcardtype',
		'title' => '__DONT_DICONV_TO_UTF8___证件类型',
		'formtype' => 'select',
		'default' => '__DONT_DICONV_TO_UTF8___身份证',
		'size' => 0,
		'choices' => array('__DONT_DICONV_TO_UTF8___身份证', '__DONT_DICONV_TO_UTF8___护照', '__DONT_DICONV_TO_UTF8___驾驶证'),
		'validate' => '',
	),
	'idcard' => array(
		'fieldid' => 'idcard',
		'title' => '__DONT_DICONV_TO_UTF8___证件号',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'address' => array(
		'fieldid' => 'address',
		'title' => '__DONT_DICONV_TO_UTF8___邮寄地址',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'zipcode' => array(
		'fieldid' => 'zipcode',
		'title' => '__DONT_DICONV_TO_UTF8___邮编',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'birthcity' => array(
		'fieldid' => 'birthcity',
		'title' => '__DONT_DICONV_TO_UTF8___出生地',
		'formtype' => 'text',
		'default' => '--',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'birthdist' => array(
		'fieldid' => 'birthdist',
		'title' => '__DONT_DICONV_TO_UTF8___出生区',
		'formtype' => 'text',
		'default' => '--',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'birthcommunity' => array(
		'fieldid' => 'birthcommunity',
		'title' => '__DONT_DICONV_TO_UTF8___出生小区',
		'formtype' => 'text',
		'default' => '--',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'residecity' => array(
		'fieldid' => 'residecity',
		'title' => '__DONT_DICONV_TO_UTF8___居住地',
		'formtype' => 'text',
		'default' => '--',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'graduateschool' => array(
		'fieldid' => 'graduateschool',
		'title' => '__DONT_DICONV_TO_UTF8___毕业学校',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'education' => array(
		'fieldid' => 'education',
		'title' => '__DONT_DICONV_TO_UTF8___学历',
		'formtype' => 'select',
		'default' => '__DONT_DICONV_TO_UTF8___其他',
		'size' => 0,
		'choices' => array('__DONT_DICONV_TO_UTF8___博士', '__DONT_DICONV_TO_UTF8___硕士', '__DONT_DICONV_TO_UTF8___本科', '__DONT_DICONV_TO_UTF8___专科', '__DONT_DICONV_TO_UTF8___中学', '__DONT_DICONV_TO_UTF8___小学', '__DONT_DICONV_TO_UTF8___其他'),
		'validate' => '',
	),
	'company' => array(
		'fieldid' => 'company',
		'title' => '__DONT_DICONV_TO_UTF8___公司',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'occupation' => array(
		'fieldid' => 'occupation',
		'title' => '__DONT_DICONV_TO_UTF8___职业',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'position' => array(
		'fieldid' => 'position',
		'title' => '__DONT_DICONV_TO_UTF8___职位',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'revenue' => array(
		'fieldid' => 'revenue',
		'title' => '__DONT_DICONV_TO_UTF8___年收入',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'affectivestatus' => array(
		'fieldid' => 'affectivestatus',
		'title' => '__DONT_DICONV_TO_UTF8___情感状态',
		'formtype' => 'text',
		'default' => '__DONT_DICONV_TO_UTF8___未婚',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'lookingfor' => array(
		'fieldid' => 'lookingfor',
		'title' => '__DONT_DICONV_TO_UTF8___交友目的',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'bloodtype' => array(
		'fieldid' => 'bloodtype',
		'title' => '__DONT_DICONV_TO_UTF8___血型',
		'formtype' => 'select',
		'default' => 'B',
		'size' => 0,
		'choices' => array('A', 'B', 'AB', 'O', '__DONT_DICONV_TO_UTF8___其它'),
		'validate' => '',
	),
	'alipay' => array(
		'fieldid' => 'alipay',
		'title' => '__DONT_DICONV_TO_UTF8___支付宝',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'qq' => array(
		'fieldid' => 'qq',
		'title' => 'QQ',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'msn' => array(
		'fieldid' => 'msn',
		'title' => 'MSN',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'taobao' => array(
		'fieldid' => 'taobao',
		'title' => '__DONT_DICONV_TO_UTF8___阿里旺旺',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'site' => array(
		'fieldid' => 'site',
		'title' => '__DONT_DICONV_TO_UTF8___个人主页',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'bio' => array(
		'fieldid' => 'bio',
		'title' => '__DONT_DICONV_TO_UTF8___自我介绍',
		'formtype' => 'textarea',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'interest' => array(
		'fieldid' => 'interest',
		'title' => '__DONT_DICONV_TO_UTF8___兴趣爱好',
		'formtype' => 'textarea',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
	'nationality' => array(
		'fieldid' => 'nationality',
		'title' => '__DONT_DICONV_TO_UTF8___国籍',
		'formtype' => 'text',
		'default' => '',
		'size' => 0,
		'choices' => array(),
		'validate' => '',
	),
);
?>
